version: '3.8'
services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FREE_PLAN_LIMIT=${FREE_PLAN_LIMIT}
    volumes:
      - ./backend/uploads:/app/uploads
    expose:
      - 4000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    volumes:
      - ./mongo-data:/data/db

# Optional: certbot service (manual steps needed to request certificates)
# You can run certbot separately to obtain certs and put them under ./certbot/conf
